### PR TITLE
2to3

### PR DESCRIPTION
**Pull request by Noordsestern**
Converted methods to Python 3

### CODE REVIEW

**Comment by foxlegend** [comment]
Hello,

I just tried your fork with a Python 3.7 interpreter. Unfortunately, I obtain the following trace:

```
Installing https://github.com/postadress/robotframework-CSVLibrary/archive/2to3.zip...
Collecting https://github.com/postadress/robotframework-CSVLibrary/archive/2to3.zip
  Downloading https://github.com/postadress/robotframework-CSVLibrary/archive/2to3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Utilisateurs\a547636\AppData\Local\Temp\pip-req-build-g0k_yduh\setup.py", line 6, in <module>
        execfile(join(dirname(__file__), 'CSVLibrary', 'version.py'))
    NameError: name 'execfile' is not defined
```
It seems that `execfile` could be replaced by `exec(open("./filename").read())`.

I hope that your work would be merged to add Python 3 support to this library :)

**Comment by thepoppingone** [comment]
Is this issue fixed?

**Comment by Noordsestern** [comment]
No. I believe, this lib is dead. However, you may pull this request and copy it direktly in your python environment. Thanks to @foxlegend it is now fully compliant. We use it since months.

**Comment by limitimil** [comment]
Here is a troubleshooting note for people who get into this error message when using the keyword **Append To Csv File**.
> TypeError: a bytes-like object is required, not 'str'

- Just change 'ab' into 'a' in this line https://github.com/postadress/robotframework-CSVLibrary/blob/a21c9edb9b487e20d240181e501e4874a7127772/CSVLibrary/__init__.py#L34
- That bug turns out to be different behavior of opening files between Python2 and Python3.

**Comment by s4int** [comment]
fixed in 0.0.3

**Pull request closed without merging**
